name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # A cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install node-fetch

      - name: Run Update Script
        env:
          PAT_1: ${{ secrets.PAT_1 }}
        run: |
          node update-readme.mjs

      - name: Commit and Push changes
        env:
          PAT_1: ${{ secrets.PAT_1 }}
        run: |
          git config --global user.name 'pereiraR3'
          git config --global user.email 'anthony_rodriguespereira@outlook.com'
          git remote set-url origin https://pereiraR3:${{ secrets.PAT_1 }}@github.com/pereiraR3/pereiraR3.git
          git add README.md
          git commit -m 'Update README'
          git push origin main
